### ISSUE TITLE
why there is not str_split! macro

### ISSUE THREAD

**Issue by alexzanderr** [Nugine/const-str#10]
i just want to split a string at compile time like this
```rust
const_str::split!("some string:another string", ":");
```

similar issue to https://github.com/rodrimati1992/const_format_crates/issues/41

**Comment by alexzanderr** [comment]
this commit, https://github.com/Nugine/const-str/commit/748a746b4bc3ae5785f3390f8366a18f26222e84, is not released on crates.io, right ?

**Comment by alexzanderr** [comment]
> 

if the macro is working and stable (i guess its stable), then yes, i need a release right now

**Comment by alexzanderr** [comment]
if the macro is working and stable (i guess its stable), then yes, i would like a release as soon as possible, thanks

**Comment by Nugine** [comment]
const-str v0.4.2 is released.
<https://docs.rs/const-str/latest/const_str/macro.split.html>

**Comment by alexzanderr** [comment]
thanks a lot!
wow, this macro is so good
