### ISSUE TITLE
Feature request: "squish" a string

### ISSUE THREAD

**Issue by shepmaster** [Nugine/const-str#14]
When writing SQL string literals, it's nice to be able to use newlines and indentation. However, all of that is unused by the database server and is better gone when logged.

Rails adds [`String#squish`](https://apidock.com/rails/String/squish):

> first removing all whitespace on both ends of the string, and then changing remaining consecutive whitespace groups into one space each.
>
> Note that it handles both ASCII and Unicode whitespace.

---

As an example, I have this SQL query in Diesel

```rust
dsl::sql_query(
    "WITH

     differences AS (
       SELECT
         lag(meter) over(ORDER BY sampled_at) AS start_meter,
         meter AS end_meter,
         lag(sampled_at) over(ORDER BY sampled_at) AS starting_at,
         sampled_at AS ending_at
       FROM
         samples
       WHERE
         transaction_id = $1
     )

     SELECT
       end_meter - start_meter as delta_meter,
       starting_at,
       ending_at
     FROM
       differences
     WHERE
       start_meter IS NOT NULL",
)
```

This generates a log message like

```
Query { sql: "WITH\n\n             differences AS (\n               SELECT\n                 lag(meter) over(ORDER BY sampled_at) AS start_meter,\n                 meter AS end_meter,\n                 lag(sampled_at) over(ORDER BY sampled_at) AS starting_at,\n                 sampled_at AS ending_at\n               FROM\n                 samples\n               WHERE\n                 transaction_id = $1\n             )\n\n             SELECT\n               end_meter - start_meter as delta_meter,\n               starting_at,\n               ending_at\n             FROM\n               differences\n             WHERE\n               start_meter IS NOT NULL", binds: [TransactionId(10)] }
```

With `squish!`, the log would be

```
Query { sql: "WITH differences AS ( SELECT lag(meter) over(ORDER BY sampled_at) AS start_meter, meter AS end_meter, lag(sampled_at) over(ORDER BY sampled_at) AS starting_at, sampled_at AS ending_at FROM samples WHERE transaction_id = $1 ) SELECT end_meter - start_meter as delta_meter, starting_at, ending_at FROM differences WHERE start_meter IS NOT NULL", binds: [TransactionId(10)] }
```

**Comment by Nugine** [comment]
It's difficult to process unicode whitespaces in const evaluation. I think only supporting ASCII whitespaces is enough for your use case.

**Comment by Nugine** [comment]
This is a runtime version:
```rust
use itertools::Itertools;

pub fn squish(input: &str) -> String {
    input.split_whitespace().join(" ")
}
```

**Comment by shepmaster** [comment]
> only supporting ASCII whitespaces is enough for your use case

yes, I think so as well. 

> in const evaluation

it’s your crate, but I wouldn’t care if the implementation was a procedural macro instead of ctfe. 

For my own education, what makes Unicode whitespace noticeably harder for this case?

**Comment by Nugine** [comment]
Checking Unicode whitespace requires a huge lookup table in libcore. See [`char::is_whitespace`](https://doc.rust-lang.org/stable/std/primitive.char.html#method.is_whitespace).

It's possible to implement `squish` by a proc macro but I prefer to keep it simple.


Finished in 130e356.

**Comment by Nugine** [comment]
[const-str v0.5.5](https://crates.io/crates/const-str/0.5.5) is released!
