### ISSUE TITLE
handle more than just literal

### ISSUE THREAD

**Issue by Stargateur** [Nugine/const-str#4]
Example:

```rust
struct Foo {}

impl Foo {
    const TIP: &'static str = "hexagons are the bestagons";
}

fn main() {
    let tip = const_str::to_shouty_snake_case!(Foo::TIP);
}
```

**Comment by Nugine** [comment]
What is the expected behavior?

```rust
let tip = const_str::to_shouty_snake_case!(Foo::TIP);
dbg!(tip); // what will be printed?
```

**Comment by Stargateur** [comment]
On this case `HEXAGONS_ARE_THE_BESTAGONS` I don't see what else, we already have the stringify macro from std if you think about `Foo::TIP`.

**Comment by Nugine** [comment]
Due to the limit of [`const fn`](https://github.com/rust-lang/rust/issues/57563) and eager expansion (#1), I don't think it is a good idea to implement this feature now.

There may be a way to work around the language limitation, but it's too complex. 
Why not write some script to generate what you want?

**Comment by Stargateur** [comment]
I'm unaware of how hard it would be.

I would prefer a Rust solution, not a I did it myself in a build that is less convenient at the long term. But that fine I can deal without this feature, but only literal greatly limit the crates and I don't see a lot of use case at the end.

**Comment by Nugine** [comment]
Now you can use [`const_str::convert_ascii_case!`](https://docs.rs/const-str/0.3.0/const_str/macro.convert_ascii_case.html).

This version (0.3.0) requires rustc 1.51.0 (const generics mvp) and adds more interesting macros ([`const_str::parse!`](https://docs.rs/const-str/0.3.0/const_str/macro.parse.html), [`const_str::to_str!`](https://docs.rs/const-str/0.3.0/const_str/macro.to_str.html), [`const_str::format!`](https://docs.rs/const-str/0.3.0/const_str/macro.format.html), ...)

```rust
struct Foo {}

impl Foo {
    const TIP: &'static str = "hexagons are the bestagons";
}

fn main() {
    let tip = const_str::convert_ascii_case!(shouty_snake, Foo::TIP);
    assert_eq!(tip, "HEXAGONS_ARE_THE_BESTAGONS");
}

```


Feel free open a issue when you find any inconsistency.
